In [ ]:
import numpy as np

### Soru 1
* 30 ile 70 arasındaki sayıları içeren bir array oluşturunuz. 
* Oluşturduğunuz array'i 4x5x2 şekline çeviriniz.
* Oluşturduğunuz array'in son boyutundaki elemanların ilkini yazdırınız. Örnek çıktı; \
[[30 32 34 36 38]\
 [40 42 44 46 48]\
 [50 52 54 56 58]\
 [60 62 64 66 68]]

In [ ]:
# Cevap

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69]
[[[30 31]
  [32 33]
  [34 35]
  [36 37]
  [38 39]]

 [[40 41]
  [42 43]
  [44 45]
  [46 47]
  [48 49]]

 [[50 51]
  [52 53]
  [54 55]
  [56 57]
  [58 59]]

 [[60 61]
  [62 63]
  [64 65]
  [66 67]
  [68 69]]]
[[30 32 34 36 38]
 [40 42 44 46 48]
 [50 52 54 56 58]
 [60 62 64 66 68]]


### Soru - 2
- Kullanicidan sirasiyla `adi, soyadi, yasi ve yasadigi sehrin plaka kodu` inputlarini alip bunlari 2x2 formatinda bir array'e cevirin. Ornek cikti su sekilde olmali:

```python
# array([['Arzu', 'Asya'],
#        ['27', '35']], dtype='<U1')
```

In [ ]:
# Cevap

Ad giriniz3
Soyad giriniz5
Yas giriniz
Plaka giriniz


array([['3', '5'],
       ['', '']], dtype='<U1')

### Soru - 3
- Alttaki kodu calistirdiginizda 3 boyutlu ve tamami sifirlardan olusan bir array elde edeceksiniz. Bu arrayin ciktisini altta belirtilen hedef ciktiya donusturmek icin gerekli basamaklari kurgulayiniz.
```python
zeros = np.array([np.zeros(10), np.zeros(10), np.zeros(10)], ndmin = 3)
zeros

# Cikti
# array([[[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
#         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
#         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]])
```
- Hedef Cikti:
# array([[[1., 0., 1., 0., 1., 0., 1., 0., 1., 0.],
#         [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#         [1., 0., 1., 0., 1., 0., 1., 0., 1., 0.]]])

In [ ]:
# Cevap

### Soru 4
Verilen array'i birim matrise çeviren bir fonksiyon yazınız.

In [ ]:
# Cevap

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


### Soru 5
* 0 ile 500 arasındaki 5'in katı olan sayılardan bir array oluşturunuz.
* Oluşturduğunuz array'i 3 boyutlu herhangi bir array'e çeviriniz.Örnek olarak: 2x5x10, 4x5x5, 1x10x10 gibi arrayler olabilir.
* Oluşturduğunuz array'in indexlerini tek tek gezerek 6'ya tam olarak bölünen değerleri bulunuz. 

In [ ]:
# Cevap

0
30
60
90
120
150
180
210
240
270
300
330
360
390
420
450
480


### Soru 6

 Bir arama fonksiyonu yazınız ve parametre olarak bir array ve aranan değeri alınız. Aranan değer array içerisinde bulunuyorsa bulunduğu index'i, bulunmuyorsa '-1' değerini döndürünüz. Bu fonksiyonu sadece 3 boyutlu arrayler için yazınız.

In [ ]:
# Cevap

[[[  0   5  10  15  20]
  [ 25  30  35  40  45]
  [ 50  55  60  65  70]
  [ 75  80  85  90  95]
  [100 105 110 115 120]]

 [[125 130 135 140 145]
  [150 155 160 165 170]
  [175 180 185 190 195]
  [200 205 210 215 220]
  [225 230 235 240 245]]

 [[250 255 260 265 270]
  [275 280 285 290 295]
  [300 305 310 315 320]
  [325 330 335 340 345]
  [350 355 360 365 370]]

 [[375 380 385 390 395]
  [400 405 410 415 420]
  [425 430 435 440 445]
  [450 455 460 465 470]
  [475 480 485 490 495]]]
(0, 1, 1)
